name: course_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  share: ^2.0.4
  url_launcher: ^6.2.6
  flutter_html: ^3.0.0-beta.2
  webview_flutter: ^4.7.0
  flutter_webview_plugin:
  sqflite: ^2.3.3+1
  icons_plus: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assetes/images/

